### ISSUE TITLE
Traduzi naive como inocente

### ISSUE THREAD

**Issue by riuri** [riuri/crowds#1]
@italohdc Seria uma palavra legal? Não acho que traduz o fato de ser apenas uma teoria mais simples, não pior ou menos esperta

**Comment by riuri** [comment]
[linha 576](https://github.com/riuri/crowds/blob/4fb98a2058ff628834964a4c8ac666e97f531225/pt.html#L576)

**Comment by italohdc** [comment]
Sim, ficou bom desse jeito! Passou bem a mensagem do que a palavra original queria dizer
