### ISSUE TITLE
Texto completo da NASA muito grande

### ISSUE THREAD

**Issue by riuri** [riuri/crowds#2]
Testado no navegador chromium em uma tela 2560x1600 (16:10)

Na região da [linha 672](https://github.com/riuri/crowds/blob/4fb98a2058ff628834964a4c8ac666e97f531225/pt.html#L672)

@italohdc

**Comment by italohdc** [comment]
Aqui ficou desse jeito! 

![screenshot from 2018-05-02 13-56-09](https://user-images.githubusercontent.com/5404234/39537827-20c06cf0-4e11-11e8-8c17-f25e8023a4bd.png)

Talvez, por mais que esteja saltando um pouco da tela, seja melhor deixar assim para não perder nenhuma informação.

**Comment by riuri** [comment]
O meu não dá kkkkkk
![captura de tela de 2018-05-02 14-02-04](https://user-images.githubusercontent.com/7346205/39537932-7512f6b0-4e11-11e8-816f-9514ae846022.png)

**Comment by italohdc** [comment]
Eu coloquei uma tag <small> no texto desse slide. Ficou menor, mas pelo menos cabe todo o conteúdo na página.

**Comment by riuri** [comment]
Boa!!
