### ISSUE TITLE
Divisão

### ISSUE THREAD

**Issue by italohdc** [riuri/crowds#4]
@riuri O que você está revisando agora? Para não estarmos trabalhando na mesma seção e dar erro de merge.

**Comment by italohdc** [comment]
Text Review:

- [x] Chapter 1
- [x] Chapter 2
- [x] Chapter 3
- [x] Chapter 4
- [x] Chapter 5
- [x] Chapter 6
- [x] Chapter 7

To-do (glitches found):

- [x] Fix yellow bar position on **Chapter 1**
- [ ] Fix red button "Start Simulation" position on first slide, **Chapter 2**  _(optional)_
- [x] Nasa text too big on **Chapter 3**
- [x] Text misaligned on **Chapter 6**

**Comment by riuri** [comment]
Eu achei uma parte sem traduzir do trabalho voluntário e do experimental. Fora isso eu troquei detalhes e mexi nos textos dos círculos.

Tem dois textos que ficaram grandes, criei issue para eles

**Comment by riuri** [comment]
O yellow bar position eu arrumei diminuindo o tamanho do texto

**Comment by riuri** [comment]
Dê uma olhada na #6 e veja qual solução fica mais legal.

Por mim, terminada essa questão, podemos fechar tudo e fazer o pull request

**Comment by italohdc** [comment]
Eu já tinha editado o #6 . Dá um pull no seu repositório local e veja se aparece.

**Comment by italohdc** [comment]
@riuri A propósito, se você não usa nenhuma interface gráfica pro git, recomendo fortemente o [GitKraken](https://www.gitkraken.com/). Ele ajuda bastante a visualizar a árvore de commits haha

**Comment by riuri** [comment]
@italohdc já me recomendaram kkkkkkkk

Não o utilizo por não ser open source e por estar satisfeito com o [gitg](https://wiki.gnome.org/Apps/Gitg/).

**Comment by italohdc** [comment]
- [ ] Fix red button "Start Simulation" position on first slide, Chapter 2 (optional)

Deixar esse assim mesmo?

**Comment by riuri** [comment]
Acho que sim, o lugar para mudar a posição está nos javascripts gerais

**Comment by riuri** [comment]
Podemos fazer o pull request?

**Comment by italohdc** [comment]
Então vamos fechar do jeito que tá!

Você acha que a gente deve colocar mais alguma informação em outro arquivo (créditos de tradução, informação de linguagem), ou só fazer o Pull Request desse jeito mesmo?

**Comment by riuri** [comment]
Desse jeito, seguimos todas as instruções do ncase
