### ISSUE TITLE
Ficou um texto em cima do outro

### ISSUE THREAD

**Issue by riuri** [riuri/crowds#5]
Nem sei como explicar, só olhe a imagem:

![captura de tela de 2018-05-02 14-13-05](https://user-images.githubusercontent.com/7346205/39538483-5ba50fc2-4e13-11e8-99a1-cbc8d79d8377.png)

**Comment by riuri** [comment]
esse bug ocorre no meu navegador no _upstream_, verifique se acontece no seu também

**Comment by italohdc** [comment]
Pelo que percebi, isso só acontece se você pular ao invés de jogar

**Comment by riuri** [comment]
então foi isso
