### ISSUE TITLE
Formatação errada no Capítulo 6

### ISSUE THREAD

**Issue by italohdc** [riuri/crowds#6]
![image](https://user-images.githubusercontent.com/5404234/39539042-0b2d27e4-4e15-11e8-8408-78dcf086b221.png)

**Comment by italohdc** [comment]
Same as #3

**Comment by riuri** [comment]
Acha que o commit f46f9df0db2ddf71c681765b153299f399bc8151 resolve o problema?

**Comment by italohdc** [comment]
Eu acho que fica melhor colocar um <small>. Porque, por mais que encaixe, fica muito denso e difícil de ser compreendido o texto.

**Comment by riuri** [comment]
O que você acha dessa redução no texto?
![captura de tela de 2018-05-02 14-57-56](https://user-images.githubusercontent.com/7346205/39540522-42b59594-4e19-11e8-9f27-6e9252e38037.png)

**Comment by italohdc** [comment]
Eu já fiz um commit com a tag <small> [commit f111b8bbc84582c496e62bbb5f2ed400355fa0e3](https://github.com/riuri/crowds/commit/f111b8bbc84582c496e62bbb5f2ed400355fa0e3)

**Comment by riuri** [comment]
Ok, vai essa então
